-- user_role_types

DROP TABLE IF EXISTS user_role_types CASCADE;

CREATE TABLE user_role_types
(
	id                 INTEGER   NOT NULL PRIMARY KEY,

	name               TEXT      NOT NULL,

	creation_timestamp TIMESTAMP NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

INSERT INTO user_role_types (id, name) VALUES (1, 'System');

-- user_roles

DROP TABLE IF EXISTS user_roles CASCADE;

CREATE TABLE user_roles
(
	id                 BIGINT    NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	uid                UUID      NOT NULL UNIQUE DEFAULT UUID_GENERATE_V4(),

	role_type_id       INTEGER   NOT NULL REFERENCES user_role_types (id) ON UPDATE CASCADE ON DELETE CASCADE,
	name               TEXT      NOT NULL,

	is_active          BOOLEAN   NOT NULL        DEFAULT TRUE,

	creation_timestamp TIMESTAMP NOT NULL        DEFAULT CLOCK_TIMESTAMP(),
	update_timestamp   TIMESTAMP NOT NULL        DEFAULT CLOCK_TIMESTAMP(),
	deletion_timestamp TIMESTAMP NULL,

	version            INTEGER   NOT NULL        DEFAULT 0
);

INSERT INTO user_roles (id, role_type_id, name) VALUES (1, 1, 'Administrator');

-- user_status

DROP TABLE IF EXISTS user_status CASCADE;

CREATE TABLE user_status
(
	id                 INTEGER   NOT NULL PRIMARY KEY,

	name               TEXT      NOT NULL,

	creation_timestamp TIMESTAMP NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

INSERT INTO user_status (id, name) VALUES (1, 'Created'), (2, 'Active');

-- users

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users
(
	id                 BIGINT    NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	uid                UUID      NOT NULL UNIQUE DEFAULT UUID_GENERATE_V4(),

	role_id            INTEGER   NOT NULL REFERENCES user_roles (id) ON UPDATE CASCADE ON DELETE CASCADE,

	first_name         TEXT      NOT NULL        DEFAULT '',
	last_name          TEXT      NOT NULL        DEFAULT '',
	display_name       TEXT      NOT NULL        DEFAULT '',

	email              TEXT      NOT NULL        DEFAULT '',
	contact_number     TEXT      NOT NULL        DEFAULT '',

	user_status_id     BIGINT    NOT NULL REFERENCES user_status (id) ON UPDATE CASCADE ON DELETE CASCADE,

	created_by         BIGINT    NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	updated_by         BIGINT    NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	deleted_by         BIGINT    NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,

	creation_timestamp TIMESTAMP NOT NULL        DEFAULT CLOCK_TIMESTAMP(),
	update_timestamp   TIMESTAMP NOT NULL        DEFAULT CLOCK_TIMESTAMP(),
	deletion_timestamp TIMESTAMP NULL,

	version            INTEGER   NOT NULL        DEFAULT 0
);

INSERT INTO users (role_id, first_name, last_name, display_name, email, user_status_id, created_by, updated_by)
VALUES (1, 'Administrator', '', 'Admin', 'admin@all-things.dev', 2, 1, 1);

-- authentication_types

DROP TABLE IF EXISTS authentication_types CASCADE;

CREATE TABLE authentication_types
(
	id                 INTEGER   NOT NULL PRIMARY KEY,

	name               TEXT      NOT NULL,

	creation_timestamp TIMESTAMP NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

INSERT INTO authentication_types (id, name) VALUES (1, 'Password');

-- authentications

DROP TABLE IF EXISTS authentications CASCADE;

CREATE TABLE authentications
(
	id                 BIGINT    NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

	user_id            BIGINT    NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	type_id            INTEGER   NOT NULL REFERENCES authentication_types (id) ON UPDATE CASCADE ON DELETE CASCADE,

	identity           TEXT      NOT NULL,
	password           TEXT      NOT NULL,

	is_active          BOOLEAN   NOT NULL DEFAULT TRUE,

	created_by         BIGINT    NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	updated_by         BIGINT    NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	deleted_by         BIGINT    NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,

	creation_timestamp TIMESTAMP NOT NULL DEFAULT CLOCK_TIMESTAMP(),
	update_timestamp   TIMESTAMP NOT NULL DEFAULT CLOCK_TIMESTAMP(),
	deletion_timestamp TIMESTAMP NULL,

	version            INTEGER   NOT NULL DEFAULT 0
);

INSERT INTO authentications (user_id, type_id, identity, password, created_by, updated_by)
VALUES (1, 1, 'admin', '', 1, 1);

