-- customers

DROP TABLE IF EXISTS customers CASCADE;

CREATE TABLE customers
(
	id      BIGINT  NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

	version INTEGER NOT NULL DEFAULT 0
);

-- user_types

DROP TABLE IF EXISTS user_role_types CASCADE;

CREATE TABLE user_role_types
(
	id                 INTEGER   NOT NULL PRIMARY KEY,

	name               TEXT      NOT NULL,

	creation_timestamp TIMESTAMP NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

INSERT INTO user_role_types (id, name) VALUES (1, 'System'), (2, 'Application');

-- user_types

DROP TABLE IF EXISTS user_roles CASCADE;

CREATE TABLE user_roles
(
	id                 INTEGER   NOT NULL PRIMARY KEY,

	role_type_id       INTEGER   NOT NULL REFERENCES user_role_types (id) ON UPDATE CASCADE ON DELETE CASCADE,

	name               TEXT      NOT NULL,

	creation_timestamp TIMESTAMP NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

INSERT INTO user_roles (id, role_type_id, name) VALUES (1, 1, 'Administrator'), (2, 2, 'Application');

-- users

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users
(
	id             BIGINT  NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

	customer_id    BIGINT  NULL REFERENCES customers (id) ON UPDATE CASCADE ON DELETE CASCADE,
	role_id        INTEGER NOT NULL REFERENCES user_roles (id) ON UPDATE CASCADE ON DELETE CASCADE,

	identity       TEXT    NOT NULL,
	email          TEXT    NOT NULL DEFAULT '',
	contact_number TEXT    NOT NULL DEFAULT '',

	version        INTEGER NOT NULL DEFAULT 0
);

INSERT INTO users (role_id, identity, email)
VALUES (1, 'admin', 'admin@all-things.dev');

-- user_identity_types

DROP TABLE IF EXISTS user_identity_types CASCADE;

CREATE TABLE user_identity_types
(
	id                 INTEGER   NOT NULL PRIMARY KEY,

	name               TEXT      NOT NULL,

	creation_timestamp TIMESTAMP NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

INSERT INTO user_identity_types (id, name)
VALUES (1, 'Username'),
	   (2, 'Email'),
	   (3, 'Mobile Number');

-- user_identities

DROP TABLE IF EXISTS user_identities CASCADE;

CREATE TABLE user_identities
(
	id                 BIGINT    NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

	user_id            BIGINT    NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	type_id            INTEGER   NOT NULL REFERENCES user_identity_types (id) ON UPDATE CASCADE ON DELETE CASCADE,

	identity           TEXT      NOT NULL,

	is_active          BOOLEAN   NOT NULL DEFAULT TRUE,

	created_by         BIGINT    NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	updated_by         BIGINT    NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	deleted_by         BIGINT    NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,

	creation_timestamp TIMESTAMP NOT NULL DEFAULT CLOCK_TIMESTAMP(),
	update_timestamp   TIMESTAMP NOT NULL DEFAULT CLOCK_TIMESTAMP(),
	deletion_timestamp TIMESTAMP NULL,

	version            INTEGER   NOT NULL DEFAULT 0
);

INSERT INTO user_identities (user_id, type_id, identity, created_by, updated_by)
VALUES (1, 1, 'admin', 1, 1),
	   (1, 2, 'admin@all-things.dev', 1, 1);

-- authentication_types

DROP TABLE IF EXISTS authentication_types CASCADE;

CREATE TABLE authentication_types
(
	id                 INTEGER   NOT NULL PRIMARY KEY,

	name               TEXT      NOT NULL,

	creation_timestamp TIMESTAMP NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

INSERT INTO authentication_types (id, name)
VALUES (1, 'Password'), (2, 'API Key');

-- authentications

DROP TABLE IF EXISTS authentications CASCADE;

CREATE TABLE authentications
(
	id                 BIGINT    NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

	user_id            BIGINT    NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	type_id            INTEGER   NOT NULL REFERENCES authentication_types (id) ON UPDATE CASCADE ON DELETE CASCADE,

	password           TEXT      NOT NULL,

	is_active          BOOLEAN   NOT NULL DEFAULT TRUE,

	created_by         BIGINT    NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	updated_by         BIGINT    NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	deleted_by         BIGINT    NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,

	creation_timestamp TIMESTAMP NOT NULL DEFAULT CLOCK_TIMESTAMP(),
	update_timestamp   TIMESTAMP NOT NULL DEFAULT CLOCK_TIMESTAMP(),
	deletion_timestamp TIMESTAMP NULL,

	version            INTEGER   NOT NULL DEFAULT 0
);

